name: Waka Readme

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *' # runs at 12 AM UTC

jobs:
    update-readme:
        name: WakaReadme DevMetrics
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - uses: athul/waka-readme@v0.3.0
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  SHOW_TITLE: true
                  BLOCKS: =>
                  TIME_RANGE: all_time
                  SHOW_TIME: true
                  SHOW_MASKED_TIME: true
                  LANG_COUNT: 5
                  SHOW_TOTAL: true
                  IGNORED_LANGUAGES: JSON Markdown TOML
                  COMMIT_MESSAGE: Updated waka-readme graph with new metrics
